### ISSUE TITLE
Requirement IDs should be visible in the rendered document

### ISSUE THREAD

**Issue by reckart** [openminted/interoperability-spec#2]
Presently, the ID is not present inside the requirements file nor is it visible in the this document. We will add an post-processing step to automatically add the ID to the rendered document.

Unfortunately, asciidoctor doesn't support the `infile` attribute now, so we'll have to cook up something outselves (or contribute to asciidoctor).

See also:
- https://github.com/asciidoctor/asciidoctor/issues/692
- https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/reader.rb#L1061-L1063

**Comment by anshul-tak** [comment]
Closed as these changes are present in the current build.
