### ISSUE TITLE
Generate the WG overviews automatically from category tags

### ISSUE THREAD

**Issue by reckart** [openminted/interoperability-spec#3]
Right now, the WG overview files need to be maintained manually:

```
WG1.adoc
WG2.adoc
WG3.adoc
WG4.adoc
```

These should be generated automatically from WG tags inside the requirements files.
- [X] Generate overview files if a single category is specified
- [x] Generated overview files should not overwrite files in GitHub repo - easiest solution: remove the existing files, then add them to `.gitignore`. More complex solution: store generated files under `target` folder
- [x] Support specifying multiple categories. Full text should only show up at the first (main) category, in the others, only a short link should show up. Categories may be comma-separated.

**Comment by reckart** [comment]
https://github.com/openminted/interoperability-spec/commit/2d893e60584c41e0ace58c11a0098235e73780af fixes "generate overview files if a single category is specified"

**Comment by reckart** [comment]
@anshul-tak thanks :) That was a good started. I extended the description above a bit.

**Comment by anshul-tak** [comment]
@reckart okay! In the next pull I will add these changes :)

**Comment by reckart** [comment]
@anshul-tak did you ever get around to implement the third point in the issue description about multiple comma-separated categories?

**Comment by anshul-tak** [comment]
@reckart No, I will work on this task

**Comment by reckart** [comment]
@anshul-tak in https://github.com/openminted/interoperability-spec/commit/5a32d33fc382871ff2d51f897972fc90a645caee I "formatted" some multi-category requirements in such a way that they don't cause an exception, but it would be better to actually have them comma-separated and handled as described above. Thanks for looking into this :)

**Comment by anshul-tak** [comment]
@reckart I have commited the changes for 3 point :) Also could you explain me what is 2 point in this issue means? I did not understood the point.
