### ISSUE TITLE
Requirement ID instead of requirement title should be used as HTML anchors

### ISSUE THREAD

**Issue by reckart** [openminted/interoperability-spec#7]
Now, asciidoc generates HTML anchors from section titles, e.g. from requirement titles. This results in rally long URLs and also breaks navigation if for some reason two requirements have the same name (should not happen, but could temporarily happen).

It should be possible to manually define the section anchors for requirements: http://asciidoctor.org/docs/user-manual/#custom-ids

**Comment by anshul-tak** [comment]
Okay, I will look into it :)

**Comment by anshul-tak** [comment]
Closed as these changes are present in current build.
